{
	"bill_id":"",
	"billed_by":"",
	"billed_time":"",
	"store":"id",
	"cd_doc_type":"store_menu_bill",
	"customer":"win",
	"total_qty":"33",
	"total_amount":"123",
	"payment_type":"cash",
	"items":[{
			"id":"12",
			"name":"name",
			"qty":"26",
			"price":"30",
			"total_price":"30*26"
		},{
			"id":"12",
			"name":"name",
			"qty":"26",
			"price":"30",
			"total_price":"30*26"
	}]
}
